spring:
  application:
    name: reporting-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:drinks_db}
    username: ${DB_USER:reporting_user}
    password: ${DB_PASSWORD:dev_password_reporting}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: reporting
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8084
