spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/drinks_db
    username: inventory_user
    password: dev_password_inventory

springdoc:
  swagger-ui:
    enabled: true

logging:
  level:
    drinks.system: DEBUG
